package report

import (
	"fmt"
	"html"
	"sort"
	"strings"

	"github.com/bryan-cox/taskledger/internal/jira"
	"github.com/bryan-cox/taskledger/internal/model"
)

// Section headers for HTML output.
const (
	htmlHeaderCompleted      = `<h2>🦀 Things I've been working on</h2>`
	htmlHeaderNextUp         = `<h2>⭐ Things I plan on working on next</h2>`
	htmlHeaderBlocked        = `<h2>🚫 Things that are blocking me</h2>`
	htmlNonFeatureWorkHeader = `Non-feature work`
)

// Inline bullet characters used instead of nested <ul> for Slack compatibility.
// Indentation uses &nbsp; to create visual hierarchy when pasted into Slack.
const (
	bulletL2 = `&nbsp;&nbsp;&nbsp;◦ `       // Second-level bullet (descriptions under tickets)
	bulletL3 = `&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ` // Third-level bullet (descriptions under non-feature sub-entries)
)

// GenerateHTML creates an HTML version of the report.
// If preloadedJiraInfo is provided (non-nil), it will be used instead of fetching from JIRA API.
func GenerateHTML(dates []string, completedTasks map[string][]model.TaskWithDate, nextUpTasks map[string][]model.TaskWithDate, blockedTasks []model.Task, preloadedJiraInfo map[string]jira.TicketInfo) string {
	// Use preloaded JIRA info if provided, otherwise fetch from API
	var jiraInfo map[string]jira.TicketInfo
	if preloadedJiraInfo != nil {
		jiraInfo = preloadedJiraInfo
	} else {
		allTickets := collectAllTickets(completedTasks, nextUpTasks, blockedTasks)
		jiraInfo = jira.ProcessTickets(allTickets)
	}

	var htmlBuilder strings.Builder

	// HTML document header
	htmlBuilder.WriteString(`<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>`)

	// Title
	htmlBuilder.WriteString(fmt.Sprintf(`<h1>Work Report (%s to %s)</h1>`, dates[0], dates[len(dates)-1]))
	htmlBuilder.WriteString(`<p><em>Autogenerated by TaskLedger</em></p>`)

	// Render each section
	htmlBuilder.WriteString(renderCompletedTasksHTML(completedTasks, jiraInfo))
	htmlBuilder.WriteString(renderNextUpTasksHTML(nextUpTasks, jiraInfo))
	htmlBuilder.WriteString(renderBlockedTasksHTML(blockedTasks, jiraInfo))

	htmlBuilder.WriteString(`</body></html>`)
	return htmlBuilder.String()
}

// collectAllTickets gathers all JIRA ticket references from categorized tasks.
func collectAllTickets(completed map[string][]model.TaskWithDate, nextUp map[string][]model.TaskWithDate, blocked []model.Task) map[string][]model.TaskWithDate {
	allTickets := make(map[string][]model.TaskWithDate)

	for ticket, tasks := range completed {
		allTickets[ticket] = tasks
	}
	for ticket, tasks := range nextUp {
		allTickets[ticket] = tasks
	}
	for _, task := range blocked {
		if task.JiraTicket != "" {
			allTickets[task.JiraTicket] = []model.TaskWithDate{{Task: task}}
		}
	}
	return allTickets
}

// deduplicateDescriptions removes duplicate descriptions and upgrades "Commented on X" to "Reviewed X"
// when both exist for the same URL.
func deduplicateDescriptions(descriptions []string) []string {
	// Track which URLs have been "Reviewed" vs "Commented on"
	reviewedURLs := make(map[string]bool)
	for _, desc := range descriptions {
		if strings.HasPrefix(desc, "Reviewed ") {
			url := strings.TrimPrefix(desc, "Reviewed ")
			reviewedURLs[url] = true
		}
	}

	seen := make(map[string]bool)
	var result []string
	for _, desc := range descriptions {
		// If "Commented on X" and we also have "Reviewed X", skip the comment
		if strings.HasPrefix(desc, "Commented on ") {
			url := strings.TrimPrefix(desc, "Commented on ")
			if reviewedURLs[url] {
				continue
			}
		}
		if !seen[desc] {
			seen[desc] = true
			result = append(result, desc)
		}
	}
	return result
}

// renderPRLinksInline renders PR links as inline text with a <br/> prefix and bullet character.
func renderPRLinksInline(prLinks map[string]bool, bullet string) string {
	if len(prLinks) == 0 {
		return ""
	}

	var links []string
	for link := range prLinks {
		links = append(links, link)
	}
	sort.Strings(links)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`<br/>%sPR(s): `, bullet))
	for i, link := range links {
		if i > 0 {
			sb.WriteString("; ")
		}
		sb.WriteString(fmt.Sprintf(`<a href="%s">%s</a>`, html.EscapeString(link), html.EscapeString(link)))
	}
	return sb.String()
}

// renderCompletedTasksHTML renders the completed tasks section as HTML.
func renderCompletedTasksHTML(tasks map[string][]model.TaskWithDate, jiraInfo map[string]jira.TicketInfo) string {
	if len(tasks) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(htmlHeaderCompleted)
	sb.WriteString(`<ul>`)

	// Separate feature work and non-feature work
	var featureTickets []string
	var nonFeatureTickets []string

	for ticket := range tasks {
		taskList := tasks[ticket]
		hasPR := false
		for _, t := range taskList {
			if t.GithubPR != "" {
				hasPR = true
				break
			}
		}

		prArg := ""
		if hasPR {
			prArg = "has-pr"
		}

		if IsNonFeatureWork(ticket, prArg) {
			nonFeatureTickets = append(nonFeatureTickets, ticket)
		} else {
			featureTickets = append(featureTickets, ticket)
		}
	}
	sort.Strings(featureTickets)
	sort.Strings(nonFeatureTickets)

	// Render feature work first
	for _, ticket := range featureTickets {
		sb.WriteString(renderTicketEntryHTML(ticket, tasks[ticket], jiraInfo))
	}

	// Render non-feature work grouped under "Non-feature work"
	if len(nonFeatureTickets) > 0 {
		sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, htmlNonFeatureWorkHeader))
		for _, ticket := range nonFeatureTickets {
			sb.WriteString(renderNonFeatureSubEntryHTML(ticket, tasks[ticket]))
		}
		sb.WriteString(`</li>`)
	}

	sb.WriteString(`</ul>`)
	return sb.String()
}

// renderTicketEntryHTML renders a single ticket entry with descriptions and PRs as inline <br/> items.
func renderTicketEntryHTML(ticket string, taskList []model.TaskWithDate, jiraInfo map[string]jira.TicketInfo) string {
	sort.Slice(taskList, func(i, j int) bool {
		return taskList[i].Date < taskList[j].Date
	})

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, jira.FormatTicketHTML(ticket, jiraInfo)))

	var descriptions []string
	prLinks := make(map[string]bool)

	for _, taskWithDate := range taskList {
		descriptions = append(descriptions, taskWithDate.GetDescriptions()...)
		if taskWithDate.GithubPR != "" {
			prLinks[taskWithDate.GithubPR] = true
		}
	}

	descriptions = deduplicateDescriptions(descriptions)
	for _, desc := range descriptions {
		sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL2, html.EscapeString(desc)))
	}
	sb.WriteString(renderPRLinksInline(prLinks, bulletL2))
	sb.WriteString(`</li>`)

	return sb.String()
}

// renderNonFeatureSubEntryHTML renders a non-feature work sub-entry using <br/> for Slack compatibility.
func renderNonFeatureSubEntryHTML(ticket string, taskList []model.TaskWithDate) string {
	sort.Slice(taskList, func(i, j int) bool {
		return taskList[i].Date < taskList[j].Date
	})

	var descriptions []string
	prLinks := make(map[string]bool)

	for _, taskWithDate := range taskList {
		descriptions = append(descriptions, taskWithDate.GetDescriptions()...)
		if taskWithDate.GithubPR != "" {
			prLinks[taskWithDate.GithubPR] = true
		}
	}

	var sb strings.Builder

	// Determine header: for synthetic keys (PR URLs, __noticket_N__), use the first description
	header := ticket
	if IsSyntheticKey(ticket) || header == "" {
		if len(descriptions) > 0 {
			header = descriptions[0]
			descriptions = descriptions[1:]
		} else {
			header = "Misc"
		}
	}
	sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL2, html.EscapeString(header)))

	descriptions = deduplicateDescriptions(descriptions)
	sort.Strings(descriptions)
	for _, desc := range descriptions {
		sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL3, html.EscapeString(desc)))
	}
	sb.WriteString(renderPRLinksInline(prLinks, bulletL3))

	return sb.String()
}

// renderNextUpTasksHTML renders the next up tasks section as HTML.
func renderNextUpTasksHTML(tasks map[string][]model.TaskWithDate, jiraInfo map[string]jira.TicketInfo) string {
	if len(tasks) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(htmlHeaderNextUp)
	sb.WriteString(`<ul>`)

	// Separate feature work and non-feature work
	var featureTickets []string
	var nonFeatureTickets []string

	for ticket := range tasks {
		taskList := tasks[ticket]
		hasPR := false
		for _, t := range taskList {
			if t.GithubPR != "" {
				hasPR = true
				break
			}
		}

		prArg := ""
		if hasPR {
			prArg = "has-pr"
		}

		if IsNonFeatureWork(ticket, prArg) {
			nonFeatureTickets = append(nonFeatureTickets, ticket)
		} else {
			featureTickets = append(featureTickets, ticket)
		}
	}
	sort.Strings(featureTickets)
	sort.Strings(nonFeatureTickets)

	// Render feature work first
	for _, ticket := range featureTickets {
		sb.WriteString(renderNextUpTicketEntryHTML(ticket, tasks[ticket], jiraInfo))
	}

	// Render non-feature work grouped under "Non-feature work"
	if len(nonFeatureTickets) > 0 {
		sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, htmlNonFeatureWorkHeader))
		for _, ticket := range nonFeatureTickets {
			sb.WriteString(renderNonFeatureNextUpSubEntryHTML(ticket, tasks[ticket]))
		}
		sb.WriteString(`</li>`)
	}

	sb.WriteString(`</ul>`)
	return sb.String()
}

// renderNextUpTicketEntryHTML renders a single next up ticket entry using inline <br/>.
func renderNextUpTicketEntryHTML(ticket string, taskList []model.TaskWithDate, jiraInfo map[string]jira.TicketInfo) string {
	sort.Slice(taskList, func(i, j int) bool {
		return taskList[i].Date < taskList[j].Date
	})

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, jira.FormatTicketHTML(ticket, jiraInfo)))

	var mostRecentDesc string
	prLinks := make(map[string]bool)

	for i := len(taskList) - 1; i >= 0; i-- {
		taskWithDate := taskList[i]
		if mostRecentDesc == "" {
			if taskWithDate.UpnextDescription != "" {
				mostRecentDesc = taskWithDate.UpnextDescription
			} else {
				allDescs := taskWithDate.GetDescriptions()
				if len(allDescs) > 0 {
					mostRecentDesc = allDescs[len(allDescs)-1]
				}
			}
		}
		if taskWithDate.GithubPR != "" {
			prLinks[taskWithDate.GithubPR] = true
		}
	}

	if mostRecentDesc != "" {
		sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL2, html.EscapeString(mostRecentDesc)))
	}
	sb.WriteString(renderPRLinksInline(prLinks, bulletL2))
	sb.WriteString(`</li>`)

	return sb.String()
}

// renderNonFeatureNextUpSubEntryHTML renders a non-feature next up sub-entry using <br/>.
func renderNonFeatureNextUpSubEntryHTML(ticket string, taskList []model.TaskWithDate) string {
	sort.Slice(taskList, func(i, j int) bool {
		return taskList[i].Date < taskList[j].Date
	})

	var mostRecentDesc string
	prLinks := make(map[string]bool)

	for i := len(taskList) - 1; i >= 0; i-- {
		taskWithDate := taskList[i]
		if mostRecentDesc == "" {
			if taskWithDate.UpnextDescription != "" {
				mostRecentDesc = taskWithDate.UpnextDescription
			} else {
				allDescs := taskWithDate.GetDescriptions()
				if len(allDescs) > 0 {
					mostRecentDesc = allDescs[len(allDescs)-1]
				}
			}
		}
		if taskWithDate.GithubPR != "" {
			prLinks[taskWithDate.GithubPR] = true
		}
	}

	var sb strings.Builder

	// Determine header: for synthetic keys, use the upnext description
	header := ticket
	if IsSyntheticKey(ticket) || header == "" {
		if mostRecentDesc != "" {
			header = mostRecentDesc
			mostRecentDesc = ""
		} else {
			header = "Misc"
		}
	}
	sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL2, html.EscapeString(header)))

	if mostRecentDesc != "" {
		sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL3, html.EscapeString(mostRecentDesc)))
	}
	sb.WriteString(renderPRLinksInline(prLinks, bulletL3))

	return sb.String()
}

// renderBlockedTasksHTML renders the blocked tasks section as HTML.
func renderBlockedTasksHTML(tasks []model.Task, jiraInfo map[string]jira.TicketInfo) string {
	if len(tasks) == 0 {
		return ""
	}

	// Separate feature work and non-feature work
	var featureTasks []model.Task
	var nonFeatureTasks []model.Task

	for _, task := range tasks {
		if IsNonFeatureWork(task.JiraTicket, task.GithubPR) {
			nonFeatureTasks = append(nonFeatureTasks, task)
		} else {
			featureTasks = append(featureTasks, task)
		}
	}

	var sb strings.Builder
	sb.WriteString(htmlHeaderBlocked)
	sb.WriteString(`<ul>`)

	// Render feature work first
	for _, task := range featureTasks {
		sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, jira.FormatTicketHTML(task.JiraTicket, jiraInfo)))
		sb.WriteString(fmt.Sprintf(`<br/>%sBlocker: %s`, bulletL2, html.EscapeString(task.Blocker)))
		sb.WriteString(`</li>`)
	}

	// Render non-feature work grouped under "Non-feature work"
	if len(nonFeatureTasks) > 0 {
		sb.WriteString(fmt.Sprintf(`<li><strong>%s</strong>`, htmlNonFeatureWorkHeader))
		for _, task := range nonFeatureTasks {
			header := task.JiraTicket
			if header == "" {
				header = "Misc"
			}
			sb.WriteString(fmt.Sprintf(`<br/>%s%s`, bulletL2, html.EscapeString(header)))
			sb.WriteString(fmt.Sprintf(`<br/>&nbsp;&nbsp;&nbsp;%sBlocker: %s`, bulletL3, html.EscapeString(task.Blocker)))
		}
		sb.WriteString(`</li>`)
	}

	sb.WriteString(`</ul>`)
	return sb.String()
}
